version: '3.8'

services:
  app:
    image: atomicorp/ossec-docker:v3.6
    restart: unless-stopped
    volumes:
      - temp:/temp
      - ./ossec-telegram-and-sns.sh:/var/ossec/active-response/bin/ossec-telegram-and-sns.sh:z
      - ./data:/var/ossec/data
    ports:
      - 514:514/udp
      - 1514:1514/udp
      - 1515:1515/tcp
    networks:
      - ossec
volumes:
  temp:
networks:
  ossec:
